/** One nationality, labeled in each of the app's 3 UI languages, for the searchable
 *  nationality picker on the client form. `fr` stays the lookup/storage key used
 *  elsewhere (existing client records are stored in French). */
export interface NationaliteEntry {
  fr: string;
  en: string;
  ar: string;
}

export const NATIONALITES: NationaliteEntry[] = [
  { fr: 'Afghane', en: 'Afghan', ar: 'أفغاني' },
  { fr: 'Albanaise', en: 'Albanian', ar: 'ألباني' },
  { fr: 'Algérienne', en: 'Algerian', ar: 'جزائري' },
  { fr: 'Allemande', en: 'German', ar: 'ألماني' },
  { fr: 'Andorrane', en: 'Andorran', ar: 'أندوري' },
  { fr: 'Angolaise', en: 'Angolan', ar: 'أنغولي' },
  { fr: 'Antiguaise-et-barbudienne', en: 'Antiguan and Barbudan', ar: 'أنتيغوي وبربودي' },
  { fr: 'Saoudienne', en: 'Saudi', ar: 'سعودي' },
  { fr: 'Argentine', en: 'Argentine', ar: 'أرجنتيني' },
  { fr: 'Arménienne', en: 'Armenian', ar: 'أرميني' },
  { fr: 'Australienne', en: 'Australian', ar: 'أسترالي' },
  { fr: 'Autrichienne', en: 'Austrian', ar: 'نمساوي' },
  { fr: 'Azerbaïdjanaise', en: 'Azerbaijani', ar: 'أذربيجاني' },
  { fr: 'Bahamienne', en: 'Bahamian', ar: 'باهامي' },
  { fr: 'Bahreïnienne', en: 'Bahraini', ar: 'بحريني' },
  { fr: 'Bangladaise', en: 'Bangladeshi', ar: 'بنغلاديشي' },
  { fr: 'Barbadienne', en: 'Barbadian', ar: 'باربادوسي' },
  { fr: 'Belge', en: 'Belgian', ar: 'بلجيكي' },
  { fr: 'Belizienne', en: 'Belizean', ar: 'بليزي' },
  { fr: 'Béninoise', en: 'Beninese', ar: 'بنيني' },
  { fr: 'Bhoutanaise', en: 'Bhutanese', ar: 'بوتاني' },
  { fr: 'Biélorusse', en: 'Belarusian', ar: 'بيلاروسي' },
  { fr: 'Birmane', en: 'Burmese', ar: 'بورمي' },
  { fr: 'Bolivienne', en: 'Bolivian', ar: 'بوليفي' },
  { fr: 'Bosnienne', en: 'Bosnian', ar: 'بوسني' },
  { fr: 'Botswanaise', en: 'Botswanan', ar: 'بوتسواني' },
  { fr: 'Brésilienne', en: 'Brazilian', ar: 'برازيلي' },
  { fr: 'Britannique', en: 'British', ar: 'بريطاني' },
  { fr: 'Brunéienne', en: 'Bruneian', ar: 'بروناوي' },
  { fr: 'Bulgare', en: 'Bulgarian', ar: 'بلغاري' },
  { fr: 'Burkinabè', en: 'Burkinabe', ar: 'بوركينابي' },
  { fr: 'Burundaise', en: 'Burundian', ar: 'بوروندي' },
  { fr: 'Cambodgienne', en: 'Cambodian', ar: 'كمبودي' },
  { fr: 'Camerounaise', en: 'Cameroonian', ar: 'كاميروني' },
  { fr: 'Canadienne', en: 'Canadian', ar: 'كندي' },
  { fr: 'Cap-verdienne', en: 'Cape Verdean', ar: 'رأس أخضري' },
  { fr: 'Centrafricaine', en: 'Central African', ar: 'إفريقي وسطي' },
  { fr: 'Chilienne', en: 'Chilean', ar: 'تشيلي' },
  { fr: 'Chinoise', en: 'Chinese', ar: 'صيني' },
  { fr: 'Chypriote', en: 'Cypriot', ar: 'قبرصي' },
  { fr: 'Colombienne', en: 'Colombian', ar: 'كولومبي' },
  { fr: 'Comorienne', en: 'Comoran', ar: 'قمري' },
  { fr: 'Congolaise', en: 'Congolese', ar: 'كونغولي' },
  { fr: 'Sud-coréenne', en: 'South Korean', ar: 'كوري جنوبي' },
  { fr: 'Nord-coréenne', en: 'North Korean', ar: 'كوري شمالي' },
  { fr: 'Costaricaine', en: 'Costa Rican', ar: 'كوستاريكي' },
  { fr: 'Ivoirienne', en: 'Ivorian', ar: 'إيفواري' },
  { fr: 'Croate', en: 'Croatian', ar: 'كرواتي' },
  { fr: 'Cubaine', en: 'Cuban', ar: 'كوبي' },
  { fr: 'Danoise', en: 'Danish', ar: 'دنماركي' },
  { fr: 'Djiboutienne', en: 'Djiboutian', ar: 'جيبوتي' },
  { fr: 'Dominicaine', en: 'Dominican', ar: 'دومينيكي' },
  { fr: 'Dominiquaise', en: 'Dominican (Dominica)', ar: 'دومينيكاني' },
  { fr: 'Égyptienne', en: 'Egyptian', ar: 'مصري' },
  { fr: 'Émirienne', en: 'Emirati', ar: 'إماراتي' },
  { fr: 'Équatorienne', en: 'Ecuadorian', ar: 'إكوادوري' },
  { fr: 'Érythréenne', en: 'Eritrean', ar: 'إريتري' },
  { fr: 'Espagnole', en: 'Spanish', ar: 'إسباني' },
  { fr: 'Estonienne', en: 'Estonian', ar: 'إستوني' },
  { fr: 'Américaine', en: 'American', ar: 'أمريكي' },
  { fr: 'Éthiopienne', en: 'Ethiopian', ar: 'إثيوبي' },
  { fr: 'Fidjienne', en: 'Fijian', ar: 'فيجي' },
  { fr: 'Finlandaise', en: 'Finnish', ar: 'فنلندي' },
  { fr: 'Française', en: 'French', ar: 'فرنسي' },
  { fr: 'Gabonaise', en: 'Gabonese', ar: 'غابوني' },
  { fr: 'Gambienne', en: 'Gambian', ar: 'غامبي' },
  { fr: 'Géorgienne', en: 'Georgian', ar: 'جورجي' },
  { fr: 'Ghanéenne', en: 'Ghanaian', ar: 'غاني' },
  { fr: 'Grecque', en: 'Greek', ar: 'يوناني' },
  { fr: 'Grenadienne', en: 'Grenadian', ar: 'غرينادي' },
  { fr: 'Guatémaltèque', en: 'Guatemalan', ar: 'غواتيمالي' },
  { fr: 'Guinéenne', en: 'Guinean', ar: 'غيني' },
  { fr: 'Bissau-guinéenne', en: 'Guinea-Bissauan', ar: 'غيني بيساوي' },
  { fr: 'Équato-guinéenne', en: 'Equatorial Guinean', ar: 'غيني استوائي' },
  { fr: 'Guyanienne', en: 'Guyanese', ar: 'غياني' },
  { fr: 'Haïtienne', en: 'Haitian', ar: 'هايتي' },
  { fr: 'Hondurienne', en: 'Honduran', ar: 'هندوراسي' },
  { fr: 'Hongroise', en: 'Hungarian', ar: 'هنغاري' },
  { fr: 'Indienne', en: 'Indian', ar: 'هندي' },
  { fr: 'Indonésienne', en: 'Indonesian', ar: 'إندونيسي' },
  { fr: 'Irakienne', en: 'Iraqi', ar: 'عراقي' },
  { fr: 'Iranienne', en: 'Iranian', ar: 'إيراني' },
  { fr: 'Irlandaise', en: 'Irish', ar: 'إيرلندي' },
  { fr: 'Islandaise', en: 'Icelandic', ar: 'آيسلندي' },
  { fr: 'Israélienne', en: 'Israeli', ar: 'إسرائيلي' },
  { fr: 'Italienne', en: 'Italian', ar: 'إيطالي' },
  { fr: 'Jamaïcaine', en: 'Jamaican', ar: 'جامايكي' },
  { fr: 'Japonaise', en: 'Japanese', ar: 'ياباني' },
  { fr: 'Jordanienne', en: 'Jordanian', ar: 'أردني' },
  { fr: 'Kazakhe', en: 'Kazakh', ar: 'كازاخستاني' },
  { fr: 'Kényane', en: 'Kenyan', ar: 'كيني' },
  { fr: 'Kirghize', en: 'Kyrgyz', ar: 'قيرغيزستاني' },
  { fr: 'Kiribatienne', en: 'Kiribati', ar: 'كيريباتي' },
  { fr: 'Koweïtienne', en: 'Kuwaiti', ar: 'كويتي' },
  { fr: 'Laotienne', en: 'Laotian', ar: 'لاوسي' },
  { fr: 'Lesothane', en: 'Basotho', ar: 'ليسوتي' },
  { fr: 'Lettone', en: 'Latvian', ar: 'لاتفي' },
  { fr: 'Libanaise', en: 'Lebanese', ar: 'لبناني' },
  { fr: 'Libérienne', en: 'Liberian', ar: 'ليبيري' },
  { fr: 'Libyenne', en: 'Libyan', ar: 'ليبي' },
  { fr: 'Liechtensteinoise', en: 'Liechtensteiner', ar: 'ليختنشتايني' },
  { fr: 'Lituanienne', en: 'Lithuanian', ar: 'ليتواني' },
  { fr: 'Luxembourgeoise', en: 'Luxembourgish', ar: 'لوكسمبورغي' },
  { fr: 'Macédonienne', en: 'Macedonian', ar: 'مقدوني' },
  { fr: 'Malgache', en: 'Malagasy', ar: 'مدغشقري' },
  { fr: 'Malaisienne', en: 'Malaysian', ar: 'ماليزي' },
  { fr: 'Malawite', en: 'Malawian', ar: 'ملاوي' },
  { fr: 'Maldivienne', en: 'Maldivian', ar: 'مالديفي' },
  { fr: 'Malienne', en: 'Malian', ar: 'مالي' },
  { fr: 'Maltaise', en: 'Maltese', ar: 'مالطي' },
  { fr: 'Marocaine', en: 'Moroccan', ar: 'مغربي' },
  { fr: 'Marshallaise', en: 'Marshallese', ar: 'مارشالي' },
  { fr: 'Mauricienne', en: 'Mauritian', ar: 'موريشيوسي' },
  { fr: 'Mauritanienne', en: 'Mauritanian', ar: 'موريتاني' },
  { fr: 'Mexicaine', en: 'Mexican', ar: 'مكسيكي' },
  { fr: 'Micronésienne', en: 'Micronesian', ar: 'ميكرونيزي' },
  { fr: 'Moldave', en: 'Moldovan', ar: 'مولدوفي' },
  { fr: 'Monégasque', en: 'Monégasque', ar: 'موناكي' },
  { fr: 'Mongole', en: 'Mongolian', ar: 'منغولي' },
  { fr: 'Monténégrine', en: 'Montenegrin', ar: 'مونتينيغري' },
  { fr: 'Mozambicaine', en: 'Mozambican', ar: 'موزمبيقي' },
  { fr: 'Namibienne', en: 'Namibian', ar: 'ناميبي' },
  { fr: 'Nauruane', en: 'Nauruan', ar: 'ناوروي' },
  { fr: 'Népalaise', en: 'Nepalese', ar: 'نيبالي' },
  { fr: 'Nicaraguayenne', en: 'Nicaraguan', ar: 'نيكاراغوي' },
  { fr: 'Nigérienne', en: 'Nigerien', ar: 'نيجري' },
  { fr: 'Nigériane', en: 'Nigerian', ar: 'نيجيري' },
  { fr: 'Norvégienne', en: 'Norwegian', ar: 'نرويجي' },
  { fr: 'Néo-zélandaise', en: 'New Zealand', ar: 'نيوزيلندي' },
  { fr: 'Omanaise', en: 'Omani', ar: 'عماني' },
  { fr: 'Néerlandaise', en: 'Dutch', ar: 'هولندي' },
  { fr: 'Ougandaise', en: 'Ugandan', ar: 'أوغندي' },
  { fr: 'Ouzbèke', en: 'Uzbek', ar: 'أوزبكستاني' },
  { fr: 'Pakistanaise', en: 'Pakistani', ar: 'باكستاني' },
  { fr: 'Palaosienne', en: 'Palauan', ar: 'بالاوي' },
  { fr: 'Palestinienne', en: 'Palestinian', ar: 'فلسطيني' },
  { fr: 'Panaméenne', en: 'Panamanian', ar: 'بنمي' },
  { fr: 'Papouasienne-néo-guinéenne', en: 'Papua New Guinean', ar: 'بابوا غيني جديد' },
  { fr: 'Paraguayenne', en: 'Paraguayan', ar: 'باراغواي' },
  { fr: 'Péruvienne', en: 'Peruvian', ar: 'بيروفي' },
  { fr: 'Philippine', en: 'Filipino', ar: 'فلبيني' },
  { fr: 'Polonaise', en: 'Polish', ar: 'بولندي' },
  { fr: 'Portugaise', en: 'Portuguese', ar: 'برتغالي' },
  { fr: 'Qatarienne', en: 'Qatari', ar: 'قطري' },
  { fr: 'Roumaine', en: 'Romanian', ar: 'روماني' },
  { fr: 'Russe', en: 'Russian', ar: 'روسي' },
  { fr: 'Rwandaise', en: 'Rwandan', ar: 'رواندي' },
  { fr: 'Salvadorienne', en: 'Salvadoran', ar: 'سلفادوري' },
  { fr: 'Samoane', en: 'Samoan', ar: 'ساموي' },
  { fr: 'Saint-marinaise', en: 'Sammarinese', ar: 'سان مارينو' },
  { fr: 'Santoméenne', en: 'São Toméan', ar: 'سان تومي' },
  { fr: 'Sénégalaise', en: 'Senegalese', ar: 'سنغالي' },
  { fr: 'Serbe', en: 'Serbian', ar: 'صربي' },
  { fr: 'Seychelloise', en: 'Seychellois', ar: 'سيشيلي' },
  { fr: 'Sierra-léonaise', en: 'Sierra Leonean', ar: 'سيراليوني' },
  { fr: 'Singapourienne', en: 'Singaporean', ar: 'سنغافوري' },
  { fr: 'Slovaque', en: 'Slovak', ar: 'سلوفاكي' },
  { fr: 'Slovène', en: 'Slovenian', ar: 'سلوفيني' },
  { fr: 'Salomonaise', en: 'Solomon Islander', ar: 'سليماني' },
  { fr: 'Somalienne', en: 'Somali', ar: 'صومالي' },
  { fr: 'Soudanaise', en: 'Sudanese', ar: 'سوداني' },
  { fr: 'Sud-soudanaise', en: 'South Sudanese', ar: 'جنوب سوداني' },
  { fr: 'Sri-lankaise', en: 'Sri Lankan', ar: 'سريلانكي' },
  { fr: 'Suédoise', en: 'Swedish', ar: 'سويدي' },
  { fr: 'Suisse', en: 'Swiss', ar: 'سويسري' },
  { fr: 'Surinamaise', en: 'Surinamese', ar: 'سورينامي' },
  { fr: 'Swazie', en: 'Swazi', ar: 'إسواتيني' },
  { fr: 'Syrienne', en: 'Syrian', ar: 'سوري' },
  { fr: 'Tadjike', en: 'Tajik', ar: 'طاجيكستاني' },
  { fr: 'Taïwanaise', en: 'Taiwanese', ar: 'تايواني' },
  { fr: 'Tanzanienne', en: 'Tanzanian', ar: 'تنزاني' },
  { fr: 'Tchadienne', en: 'Chadian', ar: 'تشادي' },
  { fr: 'Tchèque', en: 'Czech', ar: 'تشيكي' },
  { fr: 'Thaïlandaise', en: 'Thai', ar: 'تايلاندي' },
  { fr: 'Est-timoraise', en: 'East Timorese', ar: 'تيموري شرقي' },
  { fr: 'Togolaise', en: 'Togolese', ar: 'توغولي' },
  { fr: 'Tongienne', en: 'Tongan', ar: 'تونغي' },
  { fr: 'Trinidadienne', en: 'Trinidadian', ar: 'ترينيدادي' },
  { fr: 'Tunisienne', en: 'Tunisian', ar: 'تونسي' },
  { fr: 'Turkmène', en: 'Turkmen', ar: 'تركمانستاني' },
  { fr: 'Turque', en: 'Turkish', ar: 'تركي' },
  { fr: 'Tuvaluane', en: 'Tuvaluan', ar: 'توفالي' },
  { fr: 'Ukrainienne', en: 'Ukrainian', ar: 'أوكراني' },
  { fr: 'Uruguayenne', en: 'Uruguayan', ar: 'أوروغواي' },
  { fr: 'Vanuatuane', en: 'Ni-Vanuatu', ar: 'فانواتي' },
  { fr: 'Vaticane', en: 'Vatican', ar: 'فاتيكاني' },
  { fr: 'Vénézuélienne', en: 'Venezuelan', ar: 'فنزويلي' },
  { fr: 'Vietnamienne', en: 'Vietnamese', ar: 'فيتنامي' },
  { fr: 'Yéménite', en: 'Yemeni', ar: 'يمني' },
  { fr: 'Zambienne', en: 'Zambian', ar: 'زامبي' },
  { fr: 'Zimbabwéenne', en: 'Zimbabwean', ar: 'زيمبابوي' },
];
